# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 16:02
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, verbose_name='Contact|title')),
                ('title_en', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact|title')),
                ('title_ru', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact|title')),
                ('url_text', models.CharField(blank=True, max_length=50, verbose_name='Contact|url_text')),
                ('url', models.CharField(max_length=100, verbose_name='Contact|url')),
                ('contact_type', models.IntegerField(choices=[(1, 'Contact|social'), (2, 'Contact|other')], verbose_name='Contact|type')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='images/contacts', verbose_name='Contact|image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Contact|created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Contact|updated')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contact|plural',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_type', models.IntegerField(choices=[(1, 'Like'), (2, 'Favorite')])),
                ('ip_address', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor.fields.RichTextField(verbose_name='News|body')),
                ('body_en', ckeditor.fields.RichTextField(null=True, verbose_name='News|body')),
                ('body_ru', ckeditor.fields.RichTextField(null=True, verbose_name='News|body')),
                ('carousel', models.BooleanField(default=False, verbose_name='News|carousel')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='images/base', verbose_name='News|image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='News|created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='News|updated')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News|plural',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Product|name')),
                ('name_en', models.CharField(max_length=40, null=True, verbose_name='Product|name')),
                ('name_ru', models.CharField(max_length=40, null=True, verbose_name='Product|name')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Product|slug')),
                ('desc', models.TextField(verbose_name='Product|desc')),
                ('desc_en', models.TextField(null=True, verbose_name='Product|desc')),
                ('desc_ru', models.TextField(null=True, verbose_name='Product|desc')),
                ('type', models.IntegerField(choices=[(1, 'Product|Insert'), (2, 'Product|Accessory')], verbose_name='Product|type')),
                ('price_byn', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Product|BYN')),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Product|USD')),
                ('base_image', imagekit.models.fields.ProcessedImageField(default='media/default.png', upload_to='images', verbose_name='Product|base_image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Product|created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Product|updated_at')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Product|plural',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(default='media/default.png', upload_to='images', verbose_name='ProductImage|image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main_app.Product', verbose_name='ProductImage|name')),
            ],
            options={
                'verbose_name': 'ProductImage',
                'verbose_name_plural': 'ProductImage|plural',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(max_length=40)),
                ('key_expires', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='main_app.Product'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
