# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('desc', models.TextField()),
                ('type', models.IntegerField(choices=[(1, 'Insert'), (2, 'Accessory')], max_length=2)),
                ('price_byn', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
