# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20161202_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('usage', models.BooleanField(default=False)),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='qrcode')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesscode', to='main_app.Product', verbose_name='Product|AccessCode')),
            ],
        ),
    ]
