# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 11:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_accesscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='AccessCode|user'),
        ),
        migrations.AlterField(
            model_name='accesscode',
            name='code',
            field=models.CharField(blank=True, max_length=40, unique=True, verbose_name='AccessCode|code'),
        ),
        migrations.AlterField(
            model_name='accesscode',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode', verbose_name='AccessCode|qrcode'),
        ),
        migrations.AlterField(
            model_name='accesscode',
            name='usage',
            field=models.BooleanField(default=False, verbose_name='AccessCode|usage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Product|slug'),
        ),
    ]
