# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20161214_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='activated',
            field=models.BooleanField(default=False, verbose_name='AccessCode|activated'),
        ),
        migrations.AddField(
            model_name='accesscode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='AccessCode|created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accesscode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='AccessCode|updated'),
        ),
    ]
